// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: proto/purchase/v1/purchase.proto

package purchasev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Purchase struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlantId           string                 `protobuf:"bytes,2,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	PlantName         string                 `protobuf:"bytes,3,opt,name=plant_name,json=plantName,proto3" json:"plant_name,omitempty"`                   // snapshot from Catalog at purchase time
	UnitPriceCents    int64                  `protobuf:"varint,4,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"` // snapshot from Catalog at purchase time
	Quantity          int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalCents        int64                  `protobuf:"varint,6,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	CustomerName      string                 `protobuf:"bytes,7,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // PENDING | COMPLETED | CANCELLED
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PlantDetailsStale bool                   `protobuf:"varint,10,opt,name=plant_details_stale,json=plantDetailsStale,proto3" json:"plant_details_stale,omitempty"` // true when Catalog was unreachable on read
	CurrentPriceCents int64                  `protobuf:"varint,11,opt,name=current_price_cents,json=currentPriceCents,proto3" json:"current_price_cents,omitempty"` // live price from Catalog (0 when stale)
	CurrentStock      int32                  `protobuf:"varint,12,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`                  // live stock from Catalog (0 when stale)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetPlantId() string {
	if x != nil {
		return x.PlantId
	}
	return ""
}

func (x *Purchase) GetPlantName() string {
	if x != nil {
		return x.PlantName
	}
	return ""
}

func (x *Purchase) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *Purchase) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Purchase) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Purchase) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Purchase) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Purchase) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Purchase) GetPlantDetailsStale() bool {
	if x != nil {
		return x.PlantDetailsStale
	}
	return false
}

func (x *Purchase) GetCurrentPriceCents() int64 {
	if x != nil {
		return x.CurrentPriceCents
	}
	return 0
}

func (x *Purchase) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

type CreatePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlantId       string                 `protobuf:"bytes,1,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CustomerName  string                 `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseRequest) Reset() {
	*x = CreatePurchaseRequest{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseRequest) ProtoMessage() {}

func (x *CreatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePurchaseRequest) GetPlantId() string {
	if x != nil {
		return x.PlantId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreatePurchaseRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type GetPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseRequest) Reset() {
	*x = GetPurchaseRequest{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseRequest) ProtoMessage() {}

func (x *GetPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseRequest.ProtoReflect.Descriptor instead.
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *GetPurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesRequest) Reset() {
	*x = ListPurchasesRequest{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesRequest) ProtoMessage() {}

func (x *ListPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesRequest.ProtoReflect.Descriptor instead.
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{3}
}

type ListPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*Purchase            `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesResponse) Reset() {
	*x = ListPurchasesResponse{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesResponse) ProtoMessage() {}

func (x *ListPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesResponse.ProtoReflect.Descriptor instead.
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *ListPurchasesResponse) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

type UpdatePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CustomerName  string                 `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePurchaseRequest) Reset() {
	*x = UpdatePurchaseRequest{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePurchaseRequest) ProtoMessage() {}

func (x *UpdatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*UpdatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePurchaseRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdatePurchaseRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *UpdatePurchaseRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeletePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePurchaseRequest) Reset() {
	*x = DeletePurchaseRequest{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePurchaseRequest) ProtoMessage() {}

func (x *DeletePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePurchaseRequest.ProtoReflect.Descriptor instead.
func (*DeletePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePurchaseResponse) Reset() {
	*x = DeletePurchaseResponse{}
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePurchaseResponse) ProtoMessage() {}

func (x *DeletePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_v1_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePurchaseResponse.ProtoReflect.Descriptor instead.
func (*DeletePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_v1_purchase_proto_rawDescGZIP(), []int{7}
}

var File_proto_purchase_v1_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_v1_purchase_proto_rawDesc = "" +
	"\n" +
	" proto/purchase/v1/purchase.proto\x12\x13nursery.purchase.v1\"\x9c\x03\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bplant_id\x18\x02 \x01(\tR\aplantId\x12\x1d\n" +
	"\n" +
	"plant_name\x18\x03 \x01(\tR\tplantName\x12(\n" +
	"\x10unit_price_cents\x18\x04 \x01(\x03R\x0eunitPriceCents\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vtotal_cents\x18\x06 \x01(\x03R\n" +
	"totalCents\x12#\n" +
	"\rcustomer_name\x18\a \x01(\tR\fcustomerName\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12.\n" +
	"\x13plant_details_stale\x18\n" +
	" \x01(\bR\x11plantDetailsStale\x12.\n" +
	"\x13current_price_cents\x18\v \x01(\x03R\x11currentPriceCents\x12#\n" +
	"\rcurrent_stock\x18\f \x01(\x05R\fcurrentStock\"s\n" +
	"\x15CreatePurchaseRequest\x12\x19\n" +
	"\bplant_id\x18\x01 \x01(\tR\aplantId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12#\n" +
	"\rcustomer_name\x18\x03 \x01(\tR\fcustomerName\"$\n" +
	"\x12GetPurchaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14ListPurchasesRequest\"T\n" +
	"\x15ListPurchasesResponse\x12;\n" +
	"\tpurchases\x18\x01 \x03(\v2\x1d.nursery.purchase.v1.PurchaseR\tpurchases\"\x80\x01\n" +
	"\x15UpdatePurchaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12#\n" +
	"\rcustomer_name\x18\x03 \x01(\tR\fcustomerName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"'\n" +
	"\x15DeletePurchaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeletePurchaseResponse2\xf5\x03\n" +
	"\x0fPurchaseService\x12[\n" +
	"\x0eCreatePurchase\x12*.nursery.purchase.v1.CreatePurchaseRequest\x1a\x1d.nursery.purchase.v1.Purchase\x12U\n" +
	"\vGetPurchase\x12'.nursery.purchase.v1.GetPurchaseRequest\x1a\x1d.nursery.purchase.v1.Purchase\x12f\n" +
	"\rListPurchases\x12).nursery.purchase.v1.ListPurchasesRequest\x1a*.nursery.purchase.v1.ListPurchasesResponse\x12[\n" +
	"\x0eUpdatePurchase\x12*.nursery.purchase.v1.UpdatePurchaseRequest\x1a\x1d.nursery.purchase.v1.Purchase\x12i\n" +
	"\x0eDeletePurchase\x12*.nursery.purchase.v1.DeletePurchaseRequest\x1a+.nursery.purchase.v1.DeletePurchaseResponseB,Z*plant-nursery/proto/purchase/v1;purchasev1b\x06proto3"

var (
	file_proto_purchase_v1_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_v1_purchase_proto_rawDescData []byte
)

func file_proto_purchase_v1_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_v1_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_v1_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_v1_purchase_proto_rawDesc), len(file_proto_purchase_v1_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_v1_purchase_proto_rawDescData
}

var file_proto_purchase_v1_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_purchase_v1_purchase_proto_goTypes = []any{
	(*Purchase)(nil),               // 0: nursery.purchase.v1.Purchase
	(*CreatePurchaseRequest)(nil),  // 1: nursery.purchase.v1.CreatePurchaseRequest
	(*GetPurchaseRequest)(nil),     // 2: nursery.purchase.v1.GetPurchaseRequest
	(*ListPurchasesRequest)(nil),   // 3: nursery.purchase.v1.ListPurchasesRequest
	(*ListPurchasesResponse)(nil),  // 4: nursery.purchase.v1.ListPurchasesResponse
	(*UpdatePurchaseRequest)(nil),  // 5: nursery.purchase.v1.UpdatePurchaseRequest
	(*DeletePurchaseRequest)(nil),  // 6: nursery.purchase.v1.DeletePurchaseRequest
	(*DeletePurchaseResponse)(nil), // 7: nursery.purchase.v1.DeletePurchaseResponse
}
var file_proto_purchase_v1_purchase_proto_depIdxs = []int32{
	0, // 0: nursery.purchase.v1.ListPurchasesResponse.purchases:type_name -> nursery.purchase.v1.Purchase
	1, // 1: nursery.purchase.v1.PurchaseService.CreatePurchase:input_type -> nursery.purchase.v1.CreatePurchaseRequest
	2, // 2: nursery.purchase.v1.PurchaseService.GetPurchase:input_type -> nursery.purchase.v1.GetPurchaseRequest
	3, // 3: nursery.purchase.v1.PurchaseService.ListPurchases:input_type -> nursery.purchase.v1.ListPurchasesRequest
	5, // 4: nursery.purchase.v1.PurchaseService.UpdatePurchase:input_type -> nursery.purchase.v1.UpdatePurchaseRequest
	6, // 5: nursery.purchase.v1.PurchaseService.DeletePurchase:input_type -> nursery.purchase.v1.DeletePurchaseRequest
	0, // 6: nursery.purchase.v1.PurchaseService.CreatePurchase:output_type -> nursery.purchase.v1.Purchase
	0, // 7: nursery.purchase.v1.PurchaseService.GetPurchase:output_type -> nursery.purchase.v1.Purchase
	4, // 8: nursery.purchase.v1.PurchaseService.ListPurchases:output_type -> nursery.purchase.v1.ListPurchasesResponse
	0, // 9: nursery.purchase.v1.PurchaseService.UpdatePurchase:output_type -> nursery.purchase.v1.Purchase
	7, // 10: nursery.purchase.v1.PurchaseService.DeletePurchase:output_type -> nursery.purchase.v1.DeletePurchaseResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_purchase_v1_purchase_proto_init() }
func file_proto_purchase_v1_purchase_proto_init() {
	if File_proto_purchase_v1_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_v1_purchase_proto_rawDesc), len(file_proto_purchase_v1_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_v1_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_v1_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_v1_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_v1_purchase_proto = out.File
	file_proto_purchase_v1_purchase_proto_goTypes = nil
	file_proto_purchase_v1_purchase_proto_depIdxs = nil
}
