// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: proto/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Species       string                 `protobuf:"bytes,3,opt,name=species,proto3" json:"species,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plant) Reset() {
	*x = Plant{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plant) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *Plant) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Plant) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Plant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreatePlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Species       string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlantRequest) Reset() {
	*x = CreatePlantRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlantRequest) ProtoMessage() {}

func (x *CreatePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlantRequest.ProtoReflect.Descriptor instead.
func (*CreatePlantRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlantRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *CreatePlantRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *CreatePlantRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetPlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlantRequest) Reset() {
	*x = GetPlantRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantRequest) ProtoMessage() {}

func (x *GetPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantRequest.ProtoReflect.Descriptor instead.
func (*GetPlantRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPlantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlantsRequest) Reset() {
	*x = ListPlantsRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlantsRequest) ProtoMessage() {}

func (x *ListPlantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlantsRequest.ProtoReflect.Descriptor instead.
func (*ListPlantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

type ListPlantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plants        []*Plant               `protobuf:"bytes,1,rep,name=plants,proto3" json:"plants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlantsResponse) Reset() {
	*x = ListPlantsResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlantsResponse) ProtoMessage() {}

func (x *ListPlantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlantsResponse.ProtoReflect.Descriptor instead.
func (*ListPlantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlantsResponse) GetPlants() []*Plant {
	if x != nil {
		return x.Plants
	}
	return nil
}

type UpdatePlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Species       string                 `protobuf:"bytes,3,opt,name=species,proto3" json:"species,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlantRequest) Reset() {
	*x = UpdatePlantRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlantRequest) ProtoMessage() {}

func (x *UpdatePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlantRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlantRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePlantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePlantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlantRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *UpdatePlantRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpdatePlantRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type DeletePlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlantRequest) Reset() {
	*x = DeletePlantRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantRequest) ProtoMessage() {}

func (x *DeletePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantRequest.ProtoReflect.Descriptor instead.
func (*DeletePlantRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePlantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlantResponse) Reset() {
	*x = DeletePlantResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantResponse) ProtoMessage() {}

func (x *DeletePlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantResponse.ProtoReflect.Descriptor instead.
func (*DeletePlantResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

var File_proto_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/catalog/v1/catalog.proto\x12\x12nursery.catalog.v1\"\x9b\x01\n" +
	"\x05Plant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x03 \x01(\tR\aspecies\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"y\n" +
	"\x12CreatePlantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"!\n" +
	"\x0fGetPlantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11ListPlantsRequest\"G\n" +
	"\x12ListPlantsResponse\x121\n" +
	"\x06plants\x18\x01 \x03(\v2\x19.nursery.catalog.v1.PlantR\x06plants\"\x89\x01\n" +
	"\x12UpdatePlantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x03 \x01(\tR\aspecies\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\"$\n" +
	"\x12DeletePlantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeletePlantResponse2\xbd\x03\n" +
	"\x0eCatalogService\x12P\n" +
	"\vCreatePlant\x12&.nursery.catalog.v1.CreatePlantRequest\x1a\x19.nursery.catalog.v1.Plant\x12J\n" +
	"\bGetPlant\x12#.nursery.catalog.v1.GetPlantRequest\x1a\x19.nursery.catalog.v1.Plant\x12[\n" +
	"\n" +
	"ListPlants\x12%.nursery.catalog.v1.ListPlantsRequest\x1a&.nursery.catalog.v1.ListPlantsResponse\x12P\n" +
	"\vUpdatePlant\x12&.nursery.catalog.v1.UpdatePlantRequest\x1a\x19.nursery.catalog.v1.Plant\x12^\n" +
	"\vDeletePlant\x12&.nursery.catalog.v1.DeletePlantRequest\x1a'.nursery.catalog.v1.DeletePlantResponseB*Z(plant-nursery/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_proto_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_v1_catalog_proto_rawDescData []byte
)

func file_proto_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_v1_catalog_proto_rawDescData
}

var file_proto_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_catalog_v1_catalog_proto_goTypes = []any{
	(*Plant)(nil),               // 0: nursery.catalog.v1.Plant
	(*CreatePlantRequest)(nil),  // 1: nursery.catalog.v1.CreatePlantRequest
	(*GetPlantRequest)(nil),     // 2: nursery.catalog.v1.GetPlantRequest
	(*ListPlantsRequest)(nil),   // 3: nursery.catalog.v1.ListPlantsRequest
	(*ListPlantsResponse)(nil),  // 4: nursery.catalog.v1.ListPlantsResponse
	(*UpdatePlantRequest)(nil),  // 5: nursery.catalog.v1.UpdatePlantRequest
	(*DeletePlantRequest)(nil),  // 6: nursery.catalog.v1.DeletePlantRequest
	(*DeletePlantResponse)(nil), // 7: nursery.catalog.v1.DeletePlantResponse
}
var file_proto_catalog_v1_catalog_proto_depIdxs = []int32{
	0, // 0: nursery.catalog.v1.ListPlantsResponse.plants:type_name -> nursery.catalog.v1.Plant
	1, // 1: nursery.catalog.v1.CatalogService.CreatePlant:input_type -> nursery.catalog.v1.CreatePlantRequest
	2, // 2: nursery.catalog.v1.CatalogService.GetPlant:input_type -> nursery.catalog.v1.GetPlantRequest
	3, // 3: nursery.catalog.v1.CatalogService.ListPlants:input_type -> nursery.catalog.v1.ListPlantsRequest
	5, // 4: nursery.catalog.v1.CatalogService.UpdatePlant:input_type -> nursery.catalog.v1.UpdatePlantRequest
	6, // 5: nursery.catalog.v1.CatalogService.DeletePlant:input_type -> nursery.catalog.v1.DeletePlantRequest
	0, // 6: nursery.catalog.v1.CatalogService.CreatePlant:output_type -> nursery.catalog.v1.Plant
	0, // 7: nursery.catalog.v1.CatalogService.GetPlant:output_type -> nursery.catalog.v1.Plant
	4, // 8: nursery.catalog.v1.CatalogService.ListPlants:output_type -> nursery.catalog.v1.ListPlantsResponse
	0, // 9: nursery.catalog.v1.CatalogService.UpdatePlant:output_type -> nursery.catalog.v1.Plant
	7, // 10: nursery.catalog.v1.CatalogService.DeletePlant:output_type -> nursery.catalog.v1.DeletePlantResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_catalog_v1_catalog_proto_init() }
func file_proto_catalog_v1_catalog_proto_init() {
	if File_proto_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_v1_catalog_proto = out.File
	file_proto_catalog_v1_catalog_proto_goTypes = nil
	file_proto_catalog_v1_catalog_proto_depIdxs = nil
}
